# Generated by Django 4.2 on 2023-04-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_students_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='location',
            name='phone_number1',
        ),
        migrations.RemoveField(
            model_name='location',
            name='phone_number2',
        ),
        migrations.RemoveField(
            model_name='location',
            name='telegram',
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number1', models.CharField(max_length=100)),
                ('phone_number2', models.CharField(max_length=100, null=True)),
                ('instagram', models.CharField(max_length=150, null=True)),
                ('telegram', models.CharField(max_length=200, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_adress', to='base.location')),
            ],
        ),
    ]
