# Generated by Django 4.2 on 2023-04-18 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_location_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('file', models.FilePathField(null=True)),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_user', to='base.teacher')),
            ],
        ),
    ]
