# Generated by Django 4.2 on 2023-04-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_ielts_delete_textbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ielts',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
