# Generated by Django 4.2 on 2023-04-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_course_image_alter_subjects_name_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='img.png', upload_to=''),
        ),
    ]
