# Generated by Django 4.2 on 2023-04-20 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(default='english', on_delete=django.db.models.deletion.CASCADE, to='base.subjects'),
        ),
    ]
