# Generated by Django 4.2 on 2023-04-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_topic_alter_contact_address_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='4317_Y7xt2pm.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='img.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img_2.png', null=True, upload_to='media/'),
        ),
    ]
